server:
   port: 8000
eureka:
   instance:
      instance-id: ${spring.application.name}
      hostname: localhost
      statusPageUrlPath: /actuator/health
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
spring:
   application:
      name: ms-cambio
   datasource:
      url: jdbc:mysql://localhost:3306/cambio?useTimezone=true&serverTimezone=UTC
      username: root
      password: postgres
      driverClassName: com.mysql.cj.jdbc.Driver
   jpa:
      hibernate:
         ddl_auto: update
      show-sql: true
   flyway:
      url: jdbc:mysql://localhost:3306/
      schemas: cambio
      user: root
      password: postgres
management:
    zipkin:
       tracing:
          endpoint: http://localhost:9411/api/v2/spans
    tracing:
        enabled: true
        sampling:
            probability: 1.0