server:
   port: 8765
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
   instance:
      preferIpAddress: true
spring:
   application:
      name: ms-gateway
   cloud:
      gateway:
         discovery:
            locator:
               enable: true
         routes:
         -  id: cambio
            uri: lb://ms-cambio
            predicates:
            - Path=/cambio/**
         -  id: book
            uri: lb://ms-book
            predicates:
            - Path=/book/**
management:
    zipkin:
       tracing:
          endpoint: http://localhost:9411/api/v2/spans
    tracing:
        enabled: true
        sampling:
            probability: 1.0